### ISSUE TITLE
Get error during making file

### ISSUE THREAD

**Issue by ysaaron** [LuisHsu/WasmVM#24]
The message I got

> src/Syscall/Call20.cpp:506:16: error: cannot initialize a variable of type 'std::int32_t' (aka 'int') with an rvalue of type 'void * std::int32_t ret = brk((void*)programbreakPtr);
> 
> make[2]: *** [src/Syscall/CMakeFiles/WasmVM_Syscall.dir/Call20.cpp.o] Error 1

`brk` function which return a void pointer is not compatible type for variable `ret`

Do I miss something causing the error?

**Comment by kevinbird61** [comment]
Sorry to keep you waiting.

The making process work fine with me( gcc version 5.4.0 ).
Can you provide your building environment?

**Comment by ysaaron** [comment]
OS: OSX
Compiler: c++ [Apple LLVM version 8.1.0 (clang-802.0.42)]
Cmake Version: version 3.9.1

I've found that cmake  choose c++ as default compiler. I'm going to use gcc to compile it again.

**Comment by kevinbird61** [comment]
OK, I've mention this case on Readme, thank for report this problem!

**Comment by LuisHsu** [comment]
@ysaaron Your running environment is OSX and the syscall is Linux system call implement.
You can disable Syscall feature in cmake configuration if you just want to run pure Wasm.

**Comment by ysaaron** [comment]
OK, thank @LuisHsu  for the solution.
